using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GooglePlacesApi
{
    public static class Types
    {
        public const string ACCOUNTING = "accounting";
        public const string AIRPORT = "airport";
        public const string AMUSEMENT_PARK = "amusement_park";
        public const string AQUARIUM = "aquarium";
        public const string ART_GALLERY = "art_gallery";
        public const string ATM = "atm";
        public const string BAKERY = "bakery";
        public const string BANK = "bank";
        public const string BAR = "bar";
        public const string BEAUTY_SALON = "beauty_salon";
        public const string BICYCLE_STORE = "bicycle_store";
        public const string BOOK_STORE = "book_store";
        public const string BOWLING_ALLEY = "bowling_alley";
        public const string BUS_STATION = "bus_station";
        public const string CAFE = "cafe";
        public const string CAMPGROUND = "campground";
        public const string CAR_DEALER = "car_dealer";
        public const string CAR_RENTAL = "car_rental";
        public const string CAR_REPAIR = "car_repair";
        public const string CAR_WASH = "car_wash";
        public const string CASINO = "casino";
        public const string CEMETERY = "cemetery";
        public const string CHURCH = "church";
        public const string CITY_HALL = "city_hall";
        public const string CLOTHING_STORE = "clothing_store";
        public const string CONVENIENCE_STORE = "convenience_store";
        public const string СOURTHOUSE = "courthouse";
        public const string DENTIST = "dentist";
        public const string DEPARTMENT_STORE = "department_store";
        public const string DOCTOR = "doctor";
        public const string ELECTRICIAN = "electrician";
        public const string ELECTRONICS_STORE = "electronics_store";

        public const string EMBASSY = "embassy";
        public const string ESTABLISHMENT = "establishment";
        public const string FINANCE = "finance";
        public const string FIRE_STATION = "fire_station";
        public const string FLORIST = "florist";
        public const string FOOD = "food";
        public const string FUNERAL_HOME = "funeral_home";
        public const string FURNITURE_STORE = "furniture_store";
        public const string GAS_STATION = "gas_station";
        public const string GENERAL_CONTRACTOR = "general_contractor";
        public const string GROCERY_OR_SUPERMARKET = "grocery_or_supermarket";
        public const string GYM = "gym";
        public const string HAIR_CARE = "hair_care";
        public const string HARDWARE_STORE = "hardware_store";
        public const string HEALTH = "health";
        public const string HINDU_TEMPLE = "hindu_temple";
        public const string HOME_GOODS_STORE = "home_goods_store";
        public const string HOSPITAL = "hospital";
        public const string INSURANCE_AGENCY = "insurance_agency";
        public const string JEWELRY_STORE = "jewelry_store";
        public const string LAUNDRY = "laundry";
        public const string LAWYER = "lawyer";
        public const string LIBRARY = "library";
        public const string LIQUOR_STORE = "liquor_store";
        public const string LOCAL_GOVERNMENT_OFFICE = "local_government_office";
        public const string LOCKSMITH = "locksmith";
        public const string LODGING = "lodging";
        public const string MEAL_DELIVERY = "meal_delivery";
        public const string MEAL_TAKEAWAY = "meal_takeaway";
        public const string MOSQUE = "mosque";
        public const string MOVIE_RENTAL = "movie_rental";
        public const string MOVIE_THEATER = "movie_theater";

        public const string MOVING_COMPANY = "moving_company";
        public const string MUSEUM = "museum";
        public const string NIGHT_CLUB = "night_club";
        public const string PAINTER = "painter";
        public const string PARK = "park";
        public const string PARKING = "parking";
        public const string PET_STORE = "pet_store";
        public const string PHARMACY = "pharmacy";
        public const string PHYSIOTHERAPIST = "physiotherapist";
        public const string PLACE_OF_WORSHIP = "place_of_worship";
        public const string PLUMBER = "plumber";
        public const string POST_OFFICE = "post_office";
        public const string REAL_ESTATE_AGENCY = "real_estate_agency";
        public const string RESTAURANT = "restaurant";
        public const string ROOFING_CONTRACTOR = "roofing_contractor";
        public const string RV_PARK = "rv_park";
        public const string SCHOOL = "school";
        public const string SHOE_STORE = "shoe_store";
        public const string SHOPPING_MALL = "shopping_mall";
        public const string SPA = "spa";
        public const string STADIUM = "stadium";
        public const string STORAGE = "storage";
        public const string STORE = "store";
        public const string SUBWAY_STATION = "subway_station";
        public const string SYNAGOGUE = "synagogue";
        public const string TAXI_STAND = "taxi_stand";
        public const string TRAIN_STATION = "train_station";
        public const string TRAVEL_AGENCY = "travel_agency";
        public const string UNIVERSITY = "university";
        public const string VETERINARY_CARE = "veterinary_care";
        public const string ZOO = "zoo";
    }
}
