using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GooglePlacesApi
{
    public class Types
    {
        public static string Accounting = "accounting";
        public static string Airport = "airport";
        public static string Amusement_park = "amusement_park";
        public static string Aquarium = "aquarium";
        public static string Art_gallery = "art_gallery";
        public static string Atm = "atm";
        public static string Bakery = "bakery";
        public static string Bank = "bank";
        public static string Bar = "bar";
        public static string Beauty_salon = "beauty_salon";
        public static string Bicycle_store = "bicycle_store";
        public static string Book_store = "book_store";
        public static string Bowling_alley = "bowling_alley";
        public static string Bus_station = "bus_station";
        public static string Cafe = "cafe";
        public static string Campground = "campground";
        public static string Car_dealer = "car_dealer";
        public static string Car_rental = "car_rental";
        public static string Car_repair = "car_repair";
        public static string Car_wash = "car_wash";
        public static string Casino = "casino";
        public static string Cemetery = "cemetery";
        public static string Church = "church";
        public static string City_hall = "city_hall";
        public static string Clothing_store = "clothing_store";
        public static string Convenience_store = "convenience_store";
        public static string Сourthouse = "courthouse";
        public static string Dentist = "dentist";
        public static string Department_store = "department_store";
        public static string Doctor = "doctor";
        public static string Electrician = "electrician";
        public static string Electronics_store = "electronics_store";

        public static string Embassy = "embassy";
        public static string Establishment = "establishment";
        public static string Finance = "finance";
        public static string Fire_station = "fire_station";
        public static string Florist = "florist";
        public static string Food = "food";
        public static string Funeral_home = "funeral_home";
        public static string Furniture_store = "furniture_store";
        public static string Gas_station = "gas_station";
        public static string General_contractor = "general_contractor";
        public static string Grocery_or_supermarket = "grocery_or_supermarket";
        public static string Gym = "gym";
        public static string Hair_care = "hair_care";
        public static string Hardware_store = "hardware_store";
        public static string Health = "health";
        public static string Hindu_temple = "hindu_temple";
        public static string Home_goods_store = "home_goods_store";
        public static string Hospital = "hospital";
        public static string Insurance_agency = "insurance_agency";
        public static string Jewelry_store = "jewelry_store";
        public static string Laundry = "laundry";
        public static string Lawyer = "lawyer";
        public static string Library = "library";
        public static string Liquor_store = "liquor_store";
        public static string Local_government_office = "local_government_office";
        public static string Locksmith = "locksmith";
        public static string Lodging = "lodging";
        public static string Meal_delivery = "meal_delivery";
        public static string Meal_takeaway = "meal_takeaway";
        public static string Mosque = "mosque";
        public static string Movie_rental = "movie_rental";
        public static string Movie_theater = "movie_theater";

        public static string Moving_company = "moving_company";
        public static string Museum = "museum";
        public static string Night_club = "night_club";
        public static string Painter = "painter";
        public static string Park = "park";
        public static string Parking = "parking";
        public static string Pet_store = "pet_store";
        public static string Pharmacy = "pharmacy";
        public static string Physiotherapist = "physiotherapist";
        public static string Place_of_worship = "place_of_worship";
        public static string Plumber = "plumber";
        public static string Post_office = "post_office";
        public static string Real_estate_agency = "real_estate_agency";
        public static string Restaurant = "restaurant";
        public static string Roofing_contractor = "roofing_contractor";
        public static string Rv_park = "rv_park";
        public static string School = "school";
        public static string Shoe_store = "shoe_store";
        public static string Shopping_mall = "shopping_mall";
        public static string Spa = "spa";
        public static string Stadium = "stadium";
        public static string Storage = "storage";
        public static string Store = "store";
        public static string Subway_station = "subway_station";
        public static string Synagogue = "synagogue";
        public static string Taxi_stand = "taxi_stand";
        public static string Train_station = "train_station";
        public static string Travel_agency = "travel_agency";
        public static string University = "university";
        public static string Veterinary_care = "veterinary_care";
        public static string Zoo = "zoo";
    }
}
